# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-18 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubTask', '0002_userwebhookinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubWebHookEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=1024)),
                ('github_user_name', models.CharField(max_length=1024)),
                ('even_id', models.CharField(max_length=1024)),
                ('event_url', models.CharField(max_length=1024)),
                ('system_user_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
